### ISSUE TITLE
執行 `npm install` 時出現 `gyp ERR! build error`

### ISSUE THREAD

**Issue by kth-tw** [cathayddt/bdk#7]
# ISSUE

## 說明 (Description)
當我執行 `npm install` 出現以下錯誤訊息
```
gyp ERR! build error
gyp ERR! stack Error: not found: make
```

## 種類 (Issue Type)
[ ] Feature Request
[*] Report Bug
[ ] Other

---
## 通報問題 (Report Bug)
**重現步驟 (Steps to Reproduce)**
1. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash`
2. `git clone https://github.com/cathayddt/bdk.git`
3. `cd bdk`
4. `nvm install $(cat .nvmrc )`
5. `npm i`

**測試環境 (Environment)**:
* OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1020-gcp x86_64)
* NodeJS Version: v12.22.7
* NPM Version: 6.14.15
* Docker Version: 20.10.9

**應呈現結果 (Expected Behavior)**

安裝過程中不應該有錯誤訊息

**實際呈現結果 (Resulted Behavior)**

```
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.11.0-1020-gcp
gyp ERR! command "/home/eugene/.nvm/versions/node/v12.22.7/bin/node" "/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eugene/bdk/node_modules/cpu-features
gyp ERR! node -v v12.22.7
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> ssh2@1.5.0 install /home/eugene/bdk/node_modules/ssh2
> node install.js

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.11.0-1020-gcp
gyp ERR! command "/home/eugene/.nvm/versions/node/v12.22.7/bin/node" "/home/eugene/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--target=v12.22.7" "rebuild"
gyp ERR! cwd /home/eugene/bdk/node_modules/ssh2/lib/protocol/crypto
gyp ERR! node -v v12.22.7
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to build optional crypto binding
```

---

## 其他說明 (Additional Context)
是缺少某些dependencies？請補充於 `README.md`

**Comment by SecondDim** [comment]
Node.js 已更新至 16.13 版，若還有出現問題，再提出 issue
